### ISSUE TITLE
Doubles Teams

### ISSUE THREAD

**Issue by xkapastel** [Honko/pokemon-team-generator#1]
I'd like to add support for Doubles to this. How did you grab the moveset data from the Smogon dex? I can see that there's a `dexSettings` object on each Pokemon's page with the data available, but I'm wondering if there's a better way to grab every single Pokemon's moveset quickly than scraping.

**Comment by Honko** [comment]
I plan to add Doubles next time I have a good chunk of time to work on this project, probably about a month from now.

To answer your questions, I get the list of Pokemon in a gen by making a post request to http://www.smogon.com/dex/_rpc/dump-basics, and then I get the moveset data for each Pokemon by making post requests to http://www.smogon.com/dex/_rpc/dump-pokemon. This is the same api Smogon's dex uses. You can see the details for the requests by looking at the traffic when you open up a dex entry.

**Comment by xkapastel** [comment]
Is this API documented anywhere? I don't see anything about it on Smogon's website or forums.

**Comment by Honko** [comment]
Not that I know of.

**Comment by Honko** [comment]
Done in https://github.com/Honko/pokemon-team-generator/commit/3dc529a4d73ddc540eb55c27588eb1439bd3e72c
